### ISSUE TITLE
다음블로그

### ISSUE THREAD

**Issue by holdonnn** [holdonnn/PyOGP#2]
http://blog.daum.net/ktg0205/725

버려야하나..

**Comment by younseunghyun** [comment]
쩝... 다음이나 네이버나 모바일로 접근하면 크롤링이 편합니다....

그럼 특정 사이트마다 다르게 해야 되는게 있긴한데...  그때 말한 것처럼 다음 애드온 달아서 하는 것처럼 하게 되니 하면 되지 않을까요?
