### ISSUE TITLE
img src relative url src문제

### ISSUE THREAD

**Issue by holdonnn** [holdonnn/PyOGP#8]
테스트를 돌려도 이미지를 열어보지 못하니까
테스트를 좀더 쌈빡하게 하고싶은데...

**Comment by polaris340** [comment]
실제 가져와야 하는  이미지 url이랑 코드로 긁어온 이미지 url이랑 같은지 확인하면 되지 않나?

**Comment by younseunghyun** [comment]
예제 url 하나만

**Comment by backjaehyun** [comment]
아하... 열어보는건 어쩔수없겟군욥..

**Comment by backjaehyun** [comment]
이미지 열어보고  url 체크하기 assertEqual해보는걸로..
